use mercurial instead of git on appveyor
Some tests fail on git version 2.6.3.windows.1.

<pre>
  1) Error:
GitAdapterTest#test_entries_branch:
NoMethodError: undefined method `identifier' for nil:NilClass
    test/unit/lib/redmine/scm/adapters/git_adapter_test.rb:464:in `test_entries_branch'

  2) Error:
GitAdapterTest#test_entries_tag:
NoMethodError: undefined method `identifier' for nil:NilClass
    test/unit/lib/redmine/scm/adapters/git_adapter_test.rb:447:in `test_entries_tag'
</pre>