test: replace "should_route" of "activities" to "assert_routing" at integration/routing_test.rb
shoulda 2.11.3 does not support Rails2 legacy route on Rails 3.0.11.

<pre>
Error:
test: wikis (plural, admin setup) should route POST /projects/ladida/wiki/destroy
to/from {:action=>"destroy", :id=>"ladida", :controller=>"wikis"}. (RoutingTest):
NameError: uninitialized constant Routing
</pre>